### ISSUE TITLE
Implementierung Filtereinstellungen

### ISSUE THREAD

**Issue by Julez404** [Julez404/haushaltsbuch#4]
**Call (example):**
$.ajax({
          type: "post",
          url: "getTransmissionStructured.php",
          dataType: 'json',
          data: { 'sort_by': 'TRANSACTION_VALUE',
          },
          success: function (data) {
            console.log(data);
          }
      });

**Parameter:**
'date'
'date_from'
'date_to'
'date_current'
'value' //FEHLT NOCH
'value_compare' //FEHLT NOCH
'sort_by'
'group_by'
'sort_order'

**Comment by Julez404** [comment]
dates = YYYY-MM-DD
value = xx.xx
sort_by = "COLUMN NAME" ex.   TRANSACTION_VALUE
sort_order = asc | desc
group_by "Column name"

**Comment by IDookii** [comment]
following parameters where implemented:

'date_current':"week || month || year"

**Comment by Julez404** [comment]
Archiving Repository
