### ISSUE TITLE
Display Verlauf line graph with monthly weekly and yearly comparison. New Variable ?

### ISSUE THREAD

**Issue by IDookii** [Julez404/haushaltsbuch#7]
for Auswertung Verlauf

I need groupings for displaying the monthly / weekly / yearly spents

Group by TRANSACTION_DATE_SPENT is already okay but displays only dailys.

A Dynamic solution for Month and Year Spent would be the yellow from the egg

Maybe one of those ideas? :

- so "group by": 'spents_by_month' ?
- maybe a second group by variable?

Auswertung->Verlauf.html line 47

**Comment by Julez404** [comment]
Archiving Repository
